mysite/cars/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name='cars'

urlpatterns = [
    # home/
    path('', views.Index.as_view(), name='index'),
    #rentcar/
    path('rentcar/', views.Rentcar.as_view(), name='rentcar'),

    path('rentcar/<int:pk>/', views.RentcarDetailView.as_view(), name='rentcar-detail'),

    path('inspection-form/', views.InspectionCreate.as_view(), name='create_inspection' ),

    path('rent-form/', views.RentCreate.as_view(), name='create_rent' ),

    path('rent/', views.RentList.as_view(), name='rent'),

    path('rent/', views.RentListP.as_view(), name='rentpost')  

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
    path('report_builder/', include('report_builder.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/cars/models.py
from django.db import models
import datetime
from employees.models import Employee
from clients.models import Client
from . import validators

# Create your models here.



class CarBrand(models.Model):
    description = models.CharField(max_length=80, verbose_name='Description')
    status = models.BooleanField(default=False, verbose_name='Inactive')

    def __str__(self):
        return self.description

class CarModel(models.Model):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    description = models.CharField(max_length=80, verbose_name='Description')
    status = models.BooleanField(default=False, verbose_name='Inactive')

    def __str__(self):
        return self.description

class CarType(models.Model):
    description = models.CharField(max_length=80, verbose_name='Description')
    status = models.BooleanField(default=False, verbose_name='Inactive')

    def __str__(self):
        return self.description

class TypeGas(models.Model):
    description = models.CharField(max_length=80, verbose_name='Description')
    status = models.BooleanField(default=False, verbose_name='Inactive')

    def __str__(self):
        return self.description

class Car(models.Model):
    car_id = models.CharField(max_length=7, verbose_name='CarID', validators=[validators.alphanumeric])
    description = models.CharField(max_length=80, verbose_name='Description', validators=[validators.alphanumeric])
    no_chassis = models.CharField(max_length=17, verbose_name='Chassis', validators=[validators.alphanumeric])
    no_engine = models.CharField(max_length=8, verbose_name='Engine', validators=[validators.alphanumeric])
    car_type = models.ForeignKey(CarType, on_delete=models.CASCADE)
    car_model = models.ForeignKey(CarModel, on_delete=models.CASCADE)
    type_gas = models.ForeignKey(TypeGas, on_delete=models.CASCADE)
    img = models.ImageField(verbose_name='CarImage', upload_to='static/img')
    status = models.BooleanField(default=False, verbose_name='Inactive')


    def __str__(self):
        return self.car_id

class Rent(models.Model):
    rent_date = models.DateField(default=datetime.date.today, verbose_name='Rent Date')
    devolution_date = models.DateField(default=datetime.date.today, verbose_name='Devolution Date')
    amount_per_day = models.FloatField(default=0.0, verbose_name='Amount per Day')
    days = models.IntegerField(verbose_name='Days')
    comments = models.CharField(max_length=80, verbose_name='Comments')
    employee = models.ForeignKey(Employee,on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    status = models.BooleanField(default=False, verbose_name='Inactive')

    def __str__(self):
        return self.client.name 

class Inspection(models.Model):
    scratches = models.BooleanField(default=False, verbose_name='Scratches')
    gasoline = models.CharField(max_length=80, verbose_name = 'Gasoline')
    spare_tire = models.BooleanField(default=False, verbose_name='Spare Tire')
    gato = models.BooleanField(default=False, verbose_name='Gato')
    tires = models.IntegerField(verbose_name='Tires')
    observation = models.TextField(max_length=180, verbose_name='Observation')
    date = models.DateField(default=datetime.date.today, verbose_name='Date')
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    



    def __str__(self):
        return self.client.name

class Meta:
    verbose_name='Car'
    verbose_name_plural='Cars'

mysite/cars/forms.py
from django import forms
from .models import Inspection, Rent, Car

class InspectionForm(forms.ModelForm):
    class Meta:
        model = Inspection
        fields = ['scratches', 'gasoline', 'spare_tire', 'gato', 'tires', 'observation', 'date', 'car', 'client', 'employee']
        widgets = {
            'date': forms.DateTimeInput(attrs={'class': 'datetime-input'})
        },
        

        
    


class RentForm(forms.ModelForm):
    class Meta:
        model = Rent
        fields = ['rent_date', 'devolution_date', 'amount_per_day','days','comments','employee','car','client']

mysite/cars/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView, CreateView
from cars.forms import InspectionForm, RentForm
from cars.models import Car, Rent
from django.urls import reverse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .util import RentResources
from django.http import HttpResponse


# Create your views here.
class Index(TemplateView):
    template_name = "cars/home.html"

class Rentcar(ListView):
    template_name = "cars/rentcar.html"
    model = Car
    paginate_by = 3
    queryset = Car.objects.filter(status=False)




   
class RentListP(ListView):
    template_name = "cars/rent.html"
    model = Rent
    success_url = '/rent/' 

    def get_context_data(self, **kwargs):

        context = super(RentListP, self).get_context_data(**kwargs)

        
        
     

        id = self.request.GET['rentid']
        rent = Rent.objects.get(pk=id)
        print(rent)
        
        context['url'] = reverse('cars:rentpost' )
        return context

    def get_success_url(self):
        rentid = self.request.session['rentid']
        rent = Rent.objects.get(pk=rentid) 
        rent.status = True
        rent.save()
        return self.success_url

       


class RentList(ListView):
    template_name = "cars/rent.html"
    model = Rent
    success_url = '/rent/'
    

    def get_context_data(self, **kwargs):

        context = super(RentList, self).get_context_data(**kwargs)
        try:
            date1 = self.request.GET['date1']
            date2 = self.request.GET['date2']
            if date1 > date2:
                context['message'] = 'datebeg cant be higher than dateend'
            queryset = Rent.objects.filter(rent_date__range=[date1, date2])
            context['object_list'] = queryset
        
        except Exception as e:
            print(e)

        
        context['url'] = reverse('cars:rent' )
        return context

    
    


class RentcarDetailView(DetailView):
    model = Car
    

    def get_object(self):
        object = super().get_object()
        return object


class InspectionCreate(CreateView):
    model = Car
    form_class = InspectionForm
    template_name = 'cars/template-form.html'
    success_url = '/rent-form/'

    def get_object(self):
        object = super().get_object()
        return object

    def get_context_data(self, **kwargs):

        context = super(InspectionCreate, self).get_context_data(**kwargs)
        car_id = self.request.GET['car_id']
        car = Car.objects.get(pk=car_id) 
        self.request.session['car_id'] = car_id
        print(car)
        context['url'] = reverse('cars:create_inspection' )
        context['name'] = 'Inspect your car'
        context['form'] = InspectionForm(initial={'car': car})
        return context
    
    def get_success_url(self):
        car_id = self.request.session['car_id']
        success_url = '/rent-form/?car_id={0}'.format(car_id) 

        return success_url



class RentCreate(CreateView):
    model = Car
    form_class = RentForm
    template_name = 'cars/template-form.html'
    success_url = '/rentcar/'

    def get_object(self):
        object = super().get_object()
        return object

    def get_context_data(self, **kwargs):
        context = super(RentCreate, self).get_context_data(**kwargs)

        car_id = self.request.GET['car_id']
        car = Car.objects.get(pk=car_id) 
        self.request.session['car_id'] = car_id
        print(car)
        context['url'] = reverse('cars:create_rent')
        context['name'] = 'Rent process'
        context['form'] = RentForm(initial={'car': car})
        return context

    def get_success_url(self):
        car_id = self.request.session['car_id']
        car = Car.objects.get(pk=car_id) 
        car.status = True
        car.save()
        return self.success_url


        
       

mysite/cars/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Rent Car</title>
  <meta charset="utf-8" /> {% load staticfiles %} {% load bootstrap %}
  <link rel='stylesheet' href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
  <link rel='stylesheet' href="{% static 'cars/css.css' %}" type="text/css" />
  <script src="{% static 'js/bootstrap.min.js'}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
    <link href="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
    <script src="//cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.17.1/moment.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap-datetimepicker/4.17.44/js/bootstrap-datetimepicker.min.js"></script>

</head>

<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#" style='font-size:32px;'>Rent Car</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cars:index' %}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cars:rentcar' %}">Cars</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cars:rent' %}">Rent</a>
    </ul>
  </div>
</nav>

<body style="background-image:url('static/img/bg.jpg');">
  <div >
    {% block content %} {% endblock %}
  </div>
</body>

</html>